version: "3"
services:  
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3306
    expose:
      - 3308
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d


